### ISSUE TITLE
Tips for generating peg parser?

### ISSUE THREAD

**Issue by sparty02** [thorbenvh8/pegjs-java#1]
I dig the work you are doing here!  I found this repo, related to the work you are doing on the prettier-java plugin.  I'm considering doing a plugin for groovy, but would need to start with a [groovy](http://groovy-lang.org/documentation.html) parser.  Do you have any guidance for generating a peg parser for a given language?  Some quick thoughts/questions:

- Where did you get [the grammer](https://github.com/thorbenvh8/pegjs-java/blob/master/src/java.peg.js)?  Did you handroll this?  If so, any guidance on what you referenced to do it/etc?  Did you get it [from here](https://github.com/mazko/jsjavaparser/blob/master/src/Java.1.7.pegjs) and just tweak it?
- Once you got the grammer, did you just generate the parser from [their online site](https://pegjs.org/online) and just copy it [here](https://github.com/thorbenvh8/pegjs-java/blob/master/lib/java.js)?
- Once you generated the parser from the grammer, I see you have a build step [here](https://github.com/thorbenvh8/pegjs-java/blob/master/package.json#L13).  What does that generate?  Is the result what you checked in [here](https://github.com/thorbenvh8/pegjs-java/blob/master/pegjs-java.js)?  Is that just a nodejs friendly module for using the parser?

Thanks in advance for any advice/help/etc!

**Comment by tvonhacht** [comment]
- Yes I got lucky with the grammer finding it there and now updating it
- This project generates me the parser from the grammer, check what "build" does (generating parser from grammer and minify it). I try it then locally, once it works I publish it and update the dependency in the prettier-java plugin. (https://github.com/thorbenvh8/prettier-java/blob/master/src/parser.js#L3L4)
- See above

Well you basically already figured it out yourself :)

I have copied the prettier-python project and changed everything to java. Basically delete the printer.js and build it depending on your needs. (Or copy this :) )

And then step by step creating the grammar and writing tests in the prettier project.

If you have more questions just open issues in the https://github.com/prettier/prettier project. They are really helpful!

And if you build your grammar from the start, keep comments in mind from the beginning. In the grammer I used it wasnt thought about in the beginning and it makes things hard sometimes now :)
And I'm not sure if I would use a node like CompilationUnit with imports package etc in it. Its maybe smart if you want to execute code. But if you care about where something is in the code and have comments and things are messy, it can get hard. Its probably better to build your grammar without this restriction. Hope this makes sense to you, just saying don't copy this grammer, think about the trade offs.

And on top create an issue on prettier/prettier for creating groovy plugin, maybe there is someone laready doing that or they will help you :)

I'm gonna close this ticket, feel free to answer to this issue anyway :)

And sorry for the missing readme of this project, this is still work in progress :)

**Comment by tvonhacht** [comment]
I'm probably gonna write my own parser from scratch after this weekend, just some combinations of the current generated parser are slow, and its nearly impossible to debug. But I already have a lot of test cases, so that is a really good way to implement my parser step by step.

**Comment by sparty02** [comment]
@thorbenvh8 Just as an FYI, I also came across [ANTLR](https://github.com/antlr/antlr4), which has the ability to target [JavaScript parser generation](https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md) and has a number of [reference grammars](https://github.com/antlr/grammars-v4) available (including Java 8 and Java 9).  I'm not totally familiar with it, but I think it actually generates the raw parse tree, and then you'd have to write a listener to create the AST from that.... but it looks interesting.

**Comment by tvonhacht** [comment]
wow thank you so much, this is amazing. So this can work as a java parser? :) I will definetly check it out this weekend :) Hopefully this is my problem solver!!!
